In [ ]:
import pandas as pd
import re
import string
from bs4 import BeautifulSoup
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk.stem.isri import ISRIStemmer
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical
from keras.layers import Embedding, Conv1D, MaxPooling1D, Flatten, Dense, Input
from keras.models import Model

In [ ]:
import pandas as pd

# Load the data from the Excel file
arabic_data = pd.read_excel('/content/6000.xlsx')

# Now, you can work with the 'arabic_data' DataFrame.


In [ ]:
import pandas as pd
import re
import string

# Load the data from the Excel file
arabic_data = pd.read_excel('/content/6000.xlsx')

# Define normalization functions
def normalize_arabic(text):
    # Your normalization code here
    return text

def deNoise(text):
    # Your denoising code here
    return text

# Remove punctuations
def remove_punctuation(text):
    translator = str.maketrans('', '', punctuations_list)
    return text.translate(translator)

# Apply preprocessing to the 'text' column
arabic_data['text'] = arabic_data['text'].apply(normalize_arabic)
arabic_data['text'] = arabic_data['text'].apply(deNoise)
arabic_data['text'] = arabic_data['text'].apply(remove_punctuation)

# Remove rows with null values
arabic_data.dropna(axis=0, thresh=None, subset=None, inplace=True)


In [ ]:
# Check the column names in your DataFrame
print(arabic_data.columns)

# Verify the structure of your loaded data


Index(['Sentences', 'Class'], dtype='object')


In [ ]:
import pandas as pd
import nltk
from bs4 import BeautifulSoup
from nltk.corpus import stopwords
from nltk.stem import ISRIStemmer

# Download NLTK resources
nltk.download('punkt')
nltk.download('stopwords')

# Define a function for text cleaning
def clean_text(text):
    # Check for NaN values
    if pd.isna(text):
        return ''  # Handle missing values by returning an empty string
    # Remove HTML tags using BeautifulSoup
    text = BeautifulSoup(text, 'html.parser').get_text()
    return text

# Apply the text cleaning function to your text data, handling missing values
arabic_data['Sentences'] = arabic_data['Sentences'].apply(clean_text)

# Initialize the ISRIStemmer
stemmer = ISRIStemmer()

# Define a function for stemming
def stem_text(text):
    words = text.split()
    stemmed_words = [stemmer.stem(word) for word in words]
    return ' '.join(stemmed_words)

# Apply stemming to your text data
arabic_data['Sentences'] = arabic_data['Sentences'].apply(stem_text)

# Define a function to remove stop words
def remove_stopwords(text, stop_words):
    words = text.split()
    filtered_words = [word for word in words if word not in stop_words]
    return ' '.join(filtered_words)

# Get the set of Arabic stop words
stop_words_arabic = set(stopwords.words("arabic"))

# Apply stop word removal to your text data
arabic_data['Sentences'] = arabic_data['Sentences'].apply(lambda x: remove_stopwords(x, stop_words_arabic))


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
<ipython-input-13-2c38cf784134>:17: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  text = BeautifulSoup(text, 'html.parser').get_text()


In [ ]:
unique_values = set(labels)
print(unique_values)


{Ellipsis, 'class2', 'class1', 'class3'}


In [ ]:
for label in labels:
    print(type(label))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'ellipsis'>


In [ ]:
from collections import Counter
value_counts = Counter(labels)
print(value_counts)


Counter({'class1': 2, 'class2': 1, 'class3': 1, Ellipsis: 1})


In [ ]:
for label in labels:
    print(label)


class1
class2
class1
class3
Ellipsis


In [ ]:
# Original labels
labels = ['class1', 'class2', 'class1', 'class3', 'Ellipsis']

# Cleaned labels (remove 'Ellipsis' and ensure uniform data type)
cleaned_labels = [label for label in labels if label != 'Ellipsis']

# Check the cleaned labels
print(cleaned_labels)


['class1', 'class2', 'class1', 'class3']


In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
labels_encoded = label_encoder.fit_transform(labels)


In [ ]:
# Print the first few rows of the dataset including labels
print(arabic_data.head())


                                           Sentences  Class
0  لدي قرح جلس نوب قدم صوت قان حدد مدة عمل حكم زر...      0
1  خدم قدم حكم يفء رسوم؟؟ وفر حمم نظف نقط حدودية؟...      0
2                               فرض ضرب دلل فكر قرر.      0
3                   ان نسر الى امم نجد رغب اعت الى .      0
4  عدد سئل الة تم عدل حكم وكأ حكم سبق كانت صرف اي...      0


In [ ]:
# Inspect the labels
print('[+] Sample labels:', labels[:10])

# Check the number of unique labels before label encoding
print('[+] Number of unique labels before encoding:', len(set(labels)))

# Label Encoding
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(labels)

# Check the number of unique labels after label encoding
print('[+] Number of unique labels after encoding:', len(set(encoded_labels)))

# Print a few encoded labels to verify
print('[+] Encoded labels:', encoded_labels[:10])

# Continue with one-hot encoding
labels = to_categorical(encoded_labels)
print(labels)


[+] Sample labels: ['class1', 'class2', 'class1', 'class3', 'Ellipsis']
[+] Number of unique labels before encoding: 4
[+] Number of unique labels after encoding: 4
[+] Encoded labels: [1 2 1 3 0]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]


# New section

# New section

In [ ]:
# Sample text data
texts = [
    "This is the first sentence.",
    "Here is the second sentence.",
    "And this is the third sentence."
]

# Rest of your code for tokenization and label encoding


In [ ]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Sample text data (replace with your actual text data)
texts = [
    "This is the first sentence.",
    "Here is the second sentence.",
    "And this is the third sentence."
]

# Sample labels (replace with your actual labels)
labels = ['class1', 'class2', 'class1']

# Tokenization
print('[+] Tokenization')
tokenizer = Tokenizer(num_words=1000)
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)
word_index = tokenizer.word_index
print('[+] The number of unique tokens:', len(word_index))
data = pad_sequences(sequences, maxlen=10)

# Label Encoding
label_encoder = LabelEncoder()
labels_encoded = label_encoder.fit_transform(labels)

# Print encoded labels
print('[+] Encoded labels:', labels_encoded)

# Now, 'data' contains your tokenized text data, and 'labels_encoded' contains your encoded class labels.


[+] Tokenization
[+] The number of unique tokens: 9
[+] Encoded labels: [0 1 0]


In [ ]:
# CNN Model
from array import array
from keras import backend as k
import tensorflow as tf
import gc

batch_sizes = [1000, 250, 500, 100]
epochs_values = [10, 15, 20, 30, 40, 50, 60]
optimizer_values = ["rmsprop", "adam", "Adadelta"]

def create_model():
    sequence_input = Input(shape=(SEQ_LEN,), dtype='int32')
    embedded_sequences = embedding_layer(sequence_input)
    l_covl = Conv1D(128, 5, activation='relu')(embedded_sequences)
    l_pooll = MaxPooling1D(5)(l_covl)
    l_cov2 = Conv1D(128, 5, activation='relu')
    l_pool2 = MaxPooling1D(5)(l_cov2)
    l_cov3 = Conv1D(128, 5, activation='relu')(l_pool2)
    l_pool3 = MaxPooling1D(35)(l_cov3)
    l_flat = Flatten()(l_pool3)
    l_dense = Dense(len(macronum), activation="relu")(l_flat)
    preds = Dense(len(macronum), activation='softmax')(l_dense)
    model = Model(sequence_input, preds)
    return model


In [ ]:
# Define the sequence length (replace with the actual sequence length you're using)
SEQ_LEN = 100


In [ ]:
# Define your create_model function
def create_model():
    model = Sequential()

    # Add layers to your CNN model
    # ...

    # Build the model
    model.build(input_shape=(None, SEQ_LEN))  # Replace SEQ_LEN with your actual sequence length

    return model


In [ ]:
# Example Arabic text data
arabic_texts = [
    "السلام عليكم ورحمة الله وبركاته",
    "هذا مثال على نص عربي للتصنيف",
    "اللغة العربية جميلة",
    # Add more Arabic text samples here
]


In [ ]:
import pandas as pd

# Example data
data = pd.DataFrame({'text': ['Arabic text 1', 'Arabic text 2', 'Arabic text 3'],
                     'label': ['class1', 'class2', 'class1']})

# Extract x and y
x = data['text']
y = data['label']


In [ ]:

# Split your dataset into training and validation sets
from sklearn.model_selection import train_test_split

# Split data into 80% training and 20% validation
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.2, random_state=42)

# Now, you can use x_train, y_train, x_val, and y_val in your model.fit() function


In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_val_encoded = label_encoder


In [ ]:
from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)  # 'texts' is a list of strings
sequences = tokenizer.texts_to_sequences(texts)


In [ ]:
from keras.preprocessing.sequence import pad_sequences

max_sequence_length = 100  # Set the desired sequence length
padded_sequences = pad_sequences(sequences, maxlen=max_sequence_length, padding='post', truncating='post')


In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
integer_labels = label_encoder.fit_transform(labels)


In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_val, y_train, y_val = train_test_split(padded_sequences, integer_labels, test_size=0.2, random_state=42)


In [ ]:
print(type(x_train))
print(type(x_val))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
print(type(y_train))
print(type(y_val))
print(y_train.shape)
print(y_val.shape)


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(2,)
(1,)


In [ ]:
expected_shape = (SEQ_LEN,)  # Replace with the actual sequence length
input_shape = x_train.shape[1:]  # Assuming the first dimension is the batch size
print("Expected Input Shape:", expected_shape)
print("Actual Input Shape:", input_shape)


Expected Input Shape: (100,)
Actual Input Shape: (100,)


In [ ]:
VOCAB_SIZE = 10000  # Adjust this based on your vocabulary size
EMBEDDING_DIM = 100  # Adjust this based on your embedding dimension
NUM_CLASSES = 10     # Adjust this based on the number of classes in your classification task


In [ ]:
from keras.utils import to_categorical

# Convert integer labels to one-hot encoded labels
y_train = to_categorical(y_train, num_classes=10)
y_val = to_categorical(y_val, num_classes=10)


In [ ]:
from tensorflow.keras.optimizers import SGD
from tensorflow.compat.v1.keras.optimizers import SGD as LegacySGD

# Define your hyperparameter values
epochs_values = [10, 20, 30]
batch_sizes = [32, 64, 128]
optimizer_values = [LegacySGD(learning_rate=0.01), Adam(learning_rate=0.001)]

# ... (the rest of your code remains the same)


In [ ]:
from tensorflow.keras.layers import Embedding, Conv1D, MaxPooling1D, Flatten, Dense, Input


In [ ]:
# Import necessary libraries
from tensorflow.keras.layers import Embedding, Conv1D, MaxPooling1D, Flatten, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import SGD  # Use legacy optimizer

# Define your hyperparameter values
epochs_values = [10, 20, 30]
batch_sizes = [32, 64, 128]

# Determine the sequence length (SEQ_LEN) based on your data
SEQ_LEN = 100  # Set the appropriate value based on your data

# Define your create_model function with the correct input shape
def create_model():
    model = Sequential()
    # Modify the input shape based on your data
    model.add(Embedding(input_dim=VOCAB_SIZE, output_dim=EMBEDDING_DIM, input_length=SEQ_LEN))
    model.add(Conv1D(128, 5, activation='relu'))
    model.add(MaxPooling1D(5))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dense(10, activation='softmax'))
    return model

# Training loop
for i in epochs_values:
    for x in batch_sizes:
        # Create and compile the model
        model = create_model()
        model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

        # Print model summary
        model.summary()

        print("------------------")
        print("Epochs: {0} - Batch Size: {1}".format(i, x))
        print("--------------------------")

        # Train the model
        history = model.fit(x_train, y_train, validation_data=(x_val, y_val), epochs=i, batch_size=x)

        print(">>>END<<<")


Model: "sequential_35"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_21 (Embedding)    (None, 100, 100)          1000000   
                                                                 
 conv1d_21 (Conv1D)          (None, 96, 128)           64128     
                                                                 
 max_pooling1d_21 (MaxPooli  (None, 19, 128)           0         
 ng1D)                                                           
                                                                 
 flatten_21 (Flatten)        (None, 2432)              0         
                                                                 
 dense_42 (Dense)            (None, 128)               311424    
                                                                 
 dense_43 (Dense)            (None, 10)                1290      
                                                     